import pandas as pd
import time
import sys
import math
from pathlib import Path

def calculate_bearing(lat1, lon1, lat2, lon2):
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    d_lon = lon2 - lon1
    y = math.sin(d_lon) * math.cos(lat2)
    x = math.cos(lat1) * math.sin(lat2) - math.sin(lat1) * math.cos(lat2) * math.cos(d_lon)
    return (math.degrees(math.atan2(y, x)) + 360) % 360

def run_smart_mock(run_dir_str):
    run_dir = Path(run_dir_str)
    points_path = run_dir / 'points.csv'
    path_file = run_dir / 'path.csv'
    
    # Starting Position (Ghent)
    lat, lon = 51.011466, 3.708731
    heading = 0.0 
    speed = 0.000008 # Approx 1.5 knots

    print(f"\n--- SMART MOCK GPS STARTING ---")
    print(f"I am now 'steering' based on the path in: {path_file}")

    while True:
        try:
            if not points_path.exists():
                time.sleep(1)
                continue

            # 1. Look at the path generated by the A* Planner
            target_heading = heading
            if path_file.exists():
                path_df = pd.read_csv(path_file)
                if len(path_df) > 1:
                    # Target the next waypoint in the path
                    next_pt = path_df.iloc[1]
                    target_heading = calculate_bearing(lat, lon, next_pt['latitude'], next_pt['longitude'])

            # 2. Smoothly turn toward the target heading (Simulating rudder physics)
            # Find shortest turn
            diff = (target_heading - heading + 180) % 360 - 180
            heading += diff * 0.3 # Turn 30% of the way each second

            # 3. Move the boat in the direction it's facing
            lat += math.cos(math.radians(heading)) * speed * 0.9 # Lat is North/South
            lon += math.sin(math.radians(heading)) * speed * 1.1 # Lon is East/West (Mercator approx)

            # 4. Save to CSV
            df = pd.read_csv(points_path)
            new_row = pd.DataFrame([{
                'id': int(df['id'].max() + 1) if not df.empty else 0,
                'category': 'gps', 'latitude': lat, 'longitude': lon, 'heading': heading
            }])
            pd.concat([df, new_row], ignore_index=True).to_csv(points_path, index=False)
            
            print(f"Steering to {target_heading:.1f}° | Current: {heading:.1f}° | Pos: {lat:.6f}, {lon:.6f}")
            time.sleep(1) 
            
        except Exception as e:
            time.sleep(0.1)

if __name__ == "__main__":
    if len(sys.argv) > 1:
        run_smart_mock(sys.argv[1])
    else:
        print("Usage: python path_execution/mock_gps.py runs/YYYY-MM-DD_HHMMSS")